# NC Chap 4

## 2.11 (Eigendecomposition of the Pauli matrices)
Find the eigenvectors, eigenvalies, and diagonal representations of the Pauli matrices. 
### Pauli matrices
$$
\sigma_0 = I = 
\begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
$$
$$
\sigma_1 = \sigma_x = X = 
\begin{bmatrix}
0 & 1 \\
1 & 0
\end{bmatrix}
$$
$$
\sigma_2 = \sigma_y = Y = 
\begin{bmatrix}
0 & -i \\
i & 0
\end{bmatrix}
$$
$$
\sigma_3 = \sigma_z = Z = 
\begin{bmatrix}
1 & 0 \\
0 & -1
\end{bmatrix}
$$

In [28]:
import numpy as np
A = np.matrix([
    ['a', 'b'],
    ['c', 'd']
])
I = np.matrix([
    [1, 0],
    [0, 1]
], dtype=complex)
X = np.matrix([
    [0, 1],
    [1, 0]
], dtype=complex)
Y = np.matrix([
    [0, -1j],
    [1j, 0]
], dtype=complex)
Z = np.matrix([
    [1, 0],
    [0, -1]
], dtype=complex)

Diagonal representation:
$$
\newcommand{\ket}[1]{\left|{#1}\right\rangle}
\newcommand{\bra}[1]{\left\langle{#1}\right|}
A = \sum_i \lambda_i \ket{i} \bra{i}
$$

In [35]:
import math
1/math.sqrt(2)

0.7071067811865475

In [29]:
eival_x, eivec_x = np.linalg.eig(X)
print(eival_x)
print(eivec_x)

[ 1.+0.j -1.+0.j]
[[ 0.70710678-0.j  0.70710678+0.j]
 [ 0.70710678+0.j -0.70710678-0.j]]


In [36]:
eival_x[0] * np.outer(I[0], I[0]) + eival_x[1] * np.outer(I[1], I[1])

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [37]:
def eigdecomp(M):
    '''
    2 x 2 eigendecomposition. 
    w, v, z = eigdecomp(M)
    w: array of eigenvalues
    v: matrix of eigenvectors. v[:,i] corresponds to w[i]
    z: diagonal matrix rep
    '''
    I = np.matrix([[1, 0], [0, 1]], dtype=complex)
    eival, eivec = np.linalg.eig(M)
    diagonal = eival[0] * np.outer(I[0], I[0]) + eival[1] * np.outer(I[1], I[1])
    return eival, eivec, diagonal


In [32]:
eigdecomp(Y)

(array([ 1.+0.j, -1.+0.j]),
 matrix([[-0.        -0.70710678j,  0.70710678+0.j        ],
         [ 0.70710678+0.j        ,  0.        -0.70710678j]]),
 array([[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]]))

In [33]:
eigdecomp(Z)

(array([ 1.+0.j, -1.+0.j]),
 matrix([[1.+0.j, 0.+0.j],
         [0.+0.j, 1.+0.j]]),
 array([[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]]))

## 4.1
Find the points on the bloch sphere wich correspond to the normalized eigenvectors of the different Pauli matrices.

### Bloch Sphere
$$
\ket{\psi} = \cos \frac{\theta}{2} \ket{0} + e^{i\phi}\sin \frac{\theta}{2} \ket{1} \\
\ket{0} = 
\begin{bmatrix}
1 \\
0
\end{bmatrix} \\
\ket{1} = 
\begin{bmatrix}
0 \\
1
\end{bmatrix}
$$

In [39]:
w, v = np.linalg.eig(X)
for i in [0, 1]: print(v[:,i])

[[0.70710678-0.j]
 [0.70710678+0.j]]
[[ 0.70710678+0.j]
 [-0.70710678-0.j]]
